name: flutter end-to-end test

# Trigger the workflow on push or pull request.
on: [push, pull_request]

# A workflow run is made up of one or more jobs.
jobs:

# id of job, a string that is unique to the "jobs" node above.
  drive_ios:
    # Creates a build matrix for your jobs. You can define different
    # variations of an environment to run each job in.
    strategy:
      # A set of different configurations of the virtual environment.
      matrix:
        device:
          - "iPhone 8"
          - "iPhone 12 Pro Max"
      # When set to true, GitHub cancels all in-progress jobs if any matrix job
      # fails.
      fail-fast: false
    # The type of machine to run the job on.
    runs-on: macos-latest
    # Contains a sequence of tasks.
    steps:
      # A name for your step to display on GitHub.
#      - name: "List all simulators"
#        run: "xcrun instruments -s"
#      - name: "Start Simulator"
#        run: |
#          UDID=$(
#            xcrun instruments -s |
#            awk \
#              -F ' *[][]' \
#              -v 'device=${{ matrix.device }}' \
#              '$1 == device { print $2 }'
#          )
#          xcrun simctl boot "${UDID:?No Simulator with this name found}"
      - name: "Start Simulator"
        # https://github.com/futureware-tech/simulator-action
        uses: futureware-tech/simulator-action@v1
        with:
          model: ${{ matrix.device }}
          erase_before_boot: true
          shutdown_after_job: true
      # The branch or tag ref that triggered the workflow will be checked out.
      # https://github.com/marketplace/actions/checkout
      - uses: actions/checkout@v2
      # Sets up a flutter environment.
      # https://github.com/marketplace/actions/flutter-action
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.10.0'
          channel: 'stable' # or: 'dev' or 'beta'
      - run: "flutter clean"
        working-directory: Space_Mapper
      - name: "Run Flutter Driver tests"
        run: "flutter drive --target=test_driver/driver.dart" 
        working-directory: Space_Mapper